[
  {:name=>"Cálculo",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Geometria Analítica",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Álgebra Linear",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Probabilidade e Estatística",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Ciência, Tecnologia e Sociedade"},
  {:name=>"Matemática Discreta",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Lógica Matemática",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Pesquisa Operacional",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Cálculo Numérico",
    :category_name=>"Modelagem e Simulação",
    :axis_name=>"Ciência, Tecnologia e Sociedade"},
  {:name=>"Física",
    :category_name=>"Modelagem e Simulação",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Algoritmos e Estruturas de Dados",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Projeto e Análise de Algoritmos",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Programação Estruturada",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Programação Orientada a Objetos",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Programação Funcional",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Programação Web",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Programação para Dispositivos ",
    :category_name=>"Sistemas Inteligentes",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Engenharia de Software",
    :category_name=>"Engenharia e Banco de Dados",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Banco de Dados",
    :category_name=>"Engenharia e Banco de Dados",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Gerência de Projetos",
    :category_name=>"Engenharia e Banco de Dados",
    :axis_name=>"Sistemas de Software"},
  {:name=>"Arquitetura de Computadores",
    :category_name=>"Conhecimentos Básicos",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Sistemas Digitais",
    :category_name=>"Sistemas Inteligentes",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Sistemas Operacionais",
    :category_name=>"Redes e Sistemas Operacionais",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Redes de Computadores",
    :category_name=>"Redes e Sistemas Operacionais",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Compiladores",
    :category_name=>"Sistemas Inteligentes",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Teoria da Computação",
    :category_name=>"Modelagem e Simulação",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Sistemas Inteligentes",
    :category_name=>"Sistemas Inteligentes",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Robótica",
    :category_name=>"Modelagem e Simulação",
    :axis_name=>"Infraestrutura de Sistemas Computacionais"},
  {:name=>"Computação Gráfica",
    :category_name=>"Modelagem e Simulação",
    :axis_name=>"Algoritmos de Alto Desempenho"},
  {:name=>"Processamento de Sinais",
    :category_name=>"Modelagem e Simulação",
    :axis_name=>"Algoritmos de Alto Desempenho"
  }
].each do |subject|
    axis = Axis.find_or_create_by!(name: subject[:axis_name])
    category = Category.find_or_create_by!(name: subject[:category_name])
    subject  = Subject.find_or_create_by!(name: subject[:name], category: category, axis: axis)

    if subject
      puts "'#{subject.name}' subject created"
    else
      puts "Did't create '#{subject[:name]}' subject"
    end
end